const translations = {
    "en": {
        "title": "Usa",
        "services": "Services",
        "prices": "Prices",
        "reviews": "Reviews",
        "contact": "Contact",
        "promotions": "Promotions",
        "logo": "./svg/logo-en.svg",
        "heroSubtitle1": "Creating design, developing turnkey websites with promotion in Google to top positions",
        "heroSubtitle2": "By contacting our web studio, you will get the best result at an affordable price for your business.",
        "orderButton": "Order a website",
        "clientsCount": "200+",
        "satisfiedClients": "Satisfied clients",
        "company-title-tran": "Why is it needed?",
        "company-title-tran1": "Site",
        "company-title-tran2": "First of all",
        "company-title-tran3": "this is a modern business!",
        "company-text": "The average user spends 6 hours a day on the internet (source GlobalWebIndex). Small, medium, and large organizations create websites to occupy a niche in the internet environment to:",
        "company-list-item1": "Tell clients and partners about themselves.",
        "company-list-item2": "Attract buyers and sell.",
        "company-list-item3": "Generate profit from sales.",
        "company-list-item4": "Save order processing time using detailed forms.",
        "company-list-item5": "Gain instant access to foreign clients.",
        "company-list-item6": "Use the website as a platform to showcase the uniqueness of your brand.",
        "partners-txt": "Simplifying processes for",
        "partners-title-txt": "Developing Your Website",
        "partners-description": "Our websites reflect the individuality of each client, their characteristics, preferences, and overall business concept. We ensure that your site becomes an extension of your company in the digital space.",
        "partners-hero-list1": "Trusted by leaders.",
        "partners-hero-list2": "Trust backed by experience.",
        "partners-hero-list3": "Constant support for our clients.",
        "partners-title": "Brands that",
        "partners-sub-title": "trust us",
        "construction-title": "Development Stages",
        "construction-subtitle": "High-quality execution of each of the listed stages is the guarantee of success for your entire project",
        "step1-title": "Order",
        "step1-text": "Leave a request and our manager will contact you within 24h.",
        "step2-title": "Needs Identification",
        "step2-text": "We will discuss all the details of the project and draw up the technical specification.",
        "step3-title": "Site Structure",
        "step3-text": "We will develop the structure of the site, its logic, and prototype of each page.",
        "step4-title": "Web Design",
        "step4-text": "We will create a unique design using the latest technologies.",
        "step5-title": "Responsive Layout",
        "step5-text": "We will make a responsive and cross-browser layout.",
        "step6-title": "CMS Integration",
        "step6-text": "We will connect the finished layout to the CMS for further site management.",
        "step7-title": "Competitor Analysis",
        "step7-text": "We conduct a thorough analysis of the industry and competition for your site.",
        "step8-title": "Testing",
        "step8-text": "We will test the site for bugs and transfer it to your server.",
        "revie-translate": "Reviews of our customers.",
        "revie-translate1": "View Reviews.",
        "review-title": "Customer Reviews",
        "review-link": "View Reviews",
        "leave-review": "Leave a Review",
        "all-reviews": "All Reviews",
        "card-title-text": "How much does website development cost!",
        "card-name1": "BUSINESS CARD WEBSITE",
        "card-subtitle1": "For modern business, developing a business card website is a great necessity",
        "card-name2": "LANDING PAGE",
        "card-subtitle2": "For those who strive to achieve the best result.",
        "card-name3": "CORPORATE",
        "card-subtitle3": "The best choice for promoting your business online.",
        "btn-item1": "ORDER",
        "fromText": "From",
        "fromText": "From",
        "currencyText": "USD",
        "currencyText": "USD",
        "fromText": "From",
        "currencyText": "USD",

        "btn-item2": "ORDER",
        "btn-item3": "ORDER",
        "buttom-box-text": "If you are ready to start, do not hesitate! Trust our experience and professionalism in developing your website. With us, your project will be implemented quickly and efficiently. Contact us!",
        "buttom-box-text1": "We work worldwide",
        "text-modal": "Leave your contact information and we will call you back",
        "label-name": "Name",
        "label-phone": "Phone",
        "label-email": "E-mail",
        "label-comment": "Comment",
        "checkbox-text": "I accept the terms and conditions of the",
        "link-policy": "Privacy Policy",
        "send-button": "Send",
        "logo": "./svg/logo-en.svg",
        "logo-modal": "./svg/logo-modal-en.svg",
        "cook-trans": "Consent to cookies",
        "cook-trans1": "This website uses cookies to help you have a better and more relevant browsing experience on the website.",
        "cook-trans2": "Learn more...",
        "cook-trans3": "Accept",
        "cook-trans4": "Reject",
        "services-title": "WE OFFER SERVICES",
        "services-sub-title": "For small and medium businesses",
        "services-description": "For a successful business, it is important to have a representative in the digital world. A website is your online representative, always in touch with your customers and providing all the necessary information about your services, products, and company. Different sites have different capabilities: the more professional the site, the greater the value it brings. By ordering a website development from us, you will get not only a modern and unique design but also an effective tool for attracting new customers and growing your business.",
        "anime-title": "WHAT WE WORK WITH",
        "services-main-title": "OUR SERVICES",
        "service-web-design-title": "Web Design",
        "service-web-design-description": "Modern web design is a combination of aesthetics and functionality that helps create effective and attractive websites. Our web design solutions make your business visible and attractive to customers, providing the best user experience.",
        "service-marketing-title": "Marketing",
        "service-marketing-description": "Effective marketing is the key to your business success. Our strategies will help you attract new customers, increase brand awareness, and boost sales. Trust us to promote your business and see real results.",
        "service-graphics-title": "Graphics",
        "service-graphics-description": "High-quality graphics are the foundation of your brand's visual appeal. Our creative solutions will help you stand out from the competition and effectively communicate your ideas to customers. Trust us to create unique visual materials for your business.",
        "service-data-analysis-title": "Data Analysis",
        "service-data-analysis-description": "Data analysis is the key to understanding your business and making informed decisions. Our data analysis services will help you identify important trends, optimize processes, and improve efficiency. Trust us to analyze your data, and we will turn it into valuable information for your success.",
        "service-app-development-title": "App Development",
        "service-app-development-description": "Create innovative and user-friendly apps with us. Our development team ensures the high quality, functionality, and security of your mobile and web applications. Trust us to bring your ideas to life, and we will help you reach new heights in the digital world.",
        "service-web-development-title": "Web Development",
        "service-web-development-description": "Professional web development is the path to success in the online space. We create user-friendly, fast, and adaptive websites that attract attention and retain visitors. Trust us to develop your web resource, and it will become an effective tool for growing your business.",
        "service-payment-systems-title": "Payment Systems",
        "service-payment-systems-description": "Reliable payment systems are the foundation of modern business. We offer the integration of secure and convenient payment solutions that ensure fast and reliable transactions. Trust us to set up your payment systems, and your customers will appreciate the convenience and security of their purchases.",
        "service-network-title": "Network",
        "service-network-description": "A modern network is the foundation of efficient and uninterrupted business operations. We offer professional setup and support of network infrastructure, ensuring high speed, reliability, and security. Trust us with your network, and we guarantee stable connectivity and optimal performance of all systems.",
        "contact-title": "Contact Us",
        "contact-description": "Please use the form below to get in touch with us. Enter your name, email address, phone, and message, and we will get back to you shortly.",
        "contact-label-name": "Name",
        "contact-placeholder-name": "Name",
        "contact-label-email": "Email",
        "contact-placeholder-email": "Email",
        "contact-label-tel": "Phone",
        "contact-placeholder-tel": "+380",
        "contact-placeholder-comment": "Message",
        "contact-submit": "Submit",
        "contact-title": "Contact Us",
        "contact-description": "Please use the form below to get in touch with us. Enter your name, email address, phone, and message, and we will get back to you shortly.",
        "contact-placeholder-name": "Name",
        "contact-placeholder-email": "Email",
        "contact-placeholder-tel": "+380",
        "contact-placeholder-comment": "Message",
        "contact-submit": "Submit",
        "prices-title": "How much does it cost to create a website",
    "prices-subtitle": "The cost of developing a website depends on many factors. The prices listed in our table are not final and may change depending on the specific requirements and tasks you set for us.",
    "prices-main-factors": "Main factors affecting the cost:",
    "prices-subtitle-factors": "Type of site: Business card, corporate site, online store, exclusive site – each type has its own characteristics and development requirements. Functionality: The more features and capabilities your site should have, the more time and resources are needed to create it. Design: Unique and complex design requires more development time, which affects the final cost. Integrations: Connecting additional services and integrations with other systems can also affect the price. Deadlines: If you need a website in the shortest possible time, this can reflect on the cost.",
    "site-type-business-card": "Business Card Website",
    "site-type-corporate": "Corporate Website",
    "site-type-online-store": "Online Store",
    "site-type-turnkey": "Turnkey Website",
    "site-type-small-business": "Website for Small and Medium Businesses",
    "site-type-large-business": "Website for Large Businesses",
    "term-from": "From",
    "term-days": "days",
    "price-from": "from",
    "currency-usd": "USD",
    "order-button": "Order",
    "price-table-desktop-header-type": "Type of site",
    "price-table-desktop-header-price": "Price, USD",
    "price-table-desktop-header-order": "Order",
    "our-approach-title": "Our approach:",
    "our-approach-subtitle": "We always focus on the needs of our clients and are ready to offer optimal solutions that match your budget capabilities. For example, for small businesses, we can offer a template site, which will be cheaper but still functional and attractive. If you need an exclusive site with unique design and extended capabilities, the cost will be higher.",
    "pricing-flexibility-title": "Pricing flexibility:",
    "pricing-flexibility-subtitle": "We are always open to discussion and flexible in pricing. Our specialists will help you determine the best option, considering your needs and capabilities. You will receive an individual approach and professional execution of each project.",
    "reviews-hero-title": "Here are some of our awards and achievements.",
        "facebook-title": "Facebook",
        "facebook-average-rating": "Average rating on Facebook",
        "facebook-rating": "4.8",
        "google-title": "Google",
        "google-average-rating": "Average rating on Google",
        "google-rating": "4.6",
        "reviewsTitle": "Customer Reviews",
        "reviewName1": "Alexander",
        "reviewText1": "The team of professionals quickly and efficiently created our corporate website. Very satisfied with the cooperation!",
        "reviewName2": "Anna",
        "reviewText2": "Great support for our site. All issues are resolved promptly and professionally. I recommend!",
        "reviewName3": "Marek",
        "reviewText3": "The team of experts quickly created our company website. Very satisfied with the cooperation!",
        "reviewName4": "Ewa",
        "reviewText4": "Excellent service and support for our online store. Very grateful for the work!",
        "reviewName5": "Igor",
        "reviewText5": "The development of our site went flawlessly. The team is always in touch and ready to help at any moment.",
        "reviewName6": "Magda",
        "reviewText6": "Great service and support for our website. Thank you very much for your work!",
        "reviewName7": "Olena",
        "reviewText7": "The website development was done very quickly and professionally. The team took into account all our wishes. We recommend!",
        "reviewName8": "Krzysztof",
        "reviewText8": "Ordering a website went smoothly. The company delivered everything on time and according to requirements. I recommend!",
        "leaveGoogleReview": "Leave a review on",
        "googleText": "Google",
        "leaveFacebookReview": "Leave a review on",
        "facebookText": "Facebook",
        "contactAdvice": "If you have any questions or would like to receive a consultation, contact us and we will be happy to help you develop a website that best meets your needs and budget.",


    },
    "pl": {
        "title": "Pl",
        "services": "Usługi",
        "prices": "Ceny",
        "reviews": "Opinię",
        "contact": "Kontakt",
        "promotions": "Promocje",
        "logo": "./svg/logo-pl.svg",
        "heroSubtitle1": "Tworzenie projektów, rozwój stron internetowych pod klucz z promocją w Google do najwyższych pozycji",
        "heroSubtitle2": "Kontaktując się z naszym studiem internetowym, uzyskasz najlepszy wynik w przystępnej cenie dla Twojej firmy.",
        "orderButton": "Zamów stronę internetową",
        "clientsCount": "200+",
        "satisfiedClients": "Zadowoleni klienci",
        "company-title-tran": "Dlaczego potrzebna?",
        "company-title-tran1": "Strona internetowa",
        "company-title-tran2": "Przede wszystkim",
        "company-title-tran3": "to nowoczesny biznes!",
        "company-text": "Przeciętny użytkownik spędza 6 godzin dziennie w internecie (źródło GlobalWebIndex). Małe, średnie i duże organizacje tworzą strony internetowe, aby zająć niszę w środowisku internetowym, aby:",
        "company-list-item1": "Opowiedzieć klientom i partnerom o sobie.",
        "company-list-item2": "Przyciągnąć kupujących i sprzedawać.",
        "company-list-item3": "Generować zysk ze sprzedaży.",
        "company-list-item4": "Oszczędzać czas przetwarzania zamówień, korzystając ze szczegółowych formularzy.",
        "company-list-item5": "Uzyskać natychmiastowy dostęp do zagranicznych klientów.",
        "company-list-item6": "Wykorzystać stronę internetową jako platformę do prezentacji unikalności Twojej marki.",
        "partners-txt": "Uproszczenie procesów dla",
        "partners-title-txt": "Tworzenia Twojej Strony",
        "partners-description": "Nasze strony internetowe odzwierciedlają indywidualność każdego klienta, jego cechy, preferencje i ogólną koncepcję biznesu. Dbamy o to, aby Twoja strona stała się przedłużeniem Twojej firmy w przestrzeni cyfrowej.",
        "partners-hero-list1": "Zaufali nam liderzy.",
        "partners-hero-list2": "Zaufanie potwierdzone doświadczeniem.",
        "partners-hero-list3": "Stałe wsparcie dla naszych klientów.",
        "partners-title": "Nasi partnerzy",
        "partners-sub-title": "ufają",
        "construction-title": "Etapy Rozwoju",
        "construction-subtitle": "Wysokiej jakości wykonanie każdego z wymienionych etapów to gwarancja sukcesu całego projektu",
        "step1-title": "Zamówienie",
        "step1-text": "Zostaw zgłoszenie, a nasz menedżer skontaktuje się z Tobą w ciągu 24 godzin.",
        "step2-title": "Identyfikacja Potrzeb",
        "step2-text": "Omówimy wszystkie szczegóły projektu i sporządzimy specyfikację techniczną.",
        "step3-title": "Struktura Strony",
        "step3-text": "Opracujemy strukturę strony, jej logikę i prototyp każdej strony.",
        "step4-title": "Projektowanie Stron",
        "step4-text": "Stworzymy unikalny projekt za pomocą najnowszych technologii.",
        "step5-title": "Układ Responsywny",
        "step5-text": "Wykonamy układ responsywny i kompatybilny z różnymi przeglądarkami.",
        "step6-title": "Integracja z CMS",
        "step6-text": "Połączymy gotowy układ z CMS do dalszego zarządzania witryną.",
        "step7-title": "Analiza Konkurencji",
        "step7-text": "Przeprowadzimy dokładną analizę branży i konkurencji dla Twojej strony.",
        "step8-title": "Testowanie",
        "step8-text": "Przetestujemy stronę pod kątem błędów i przeniesiemy ją na Twój serwer.",
        "revie-translate": "Opinie naszych klientów.",
        "revie-translate1": "Zobacz opinie.",
        "review-title": "Opinie klientów",
        "review-link": "Zobacz Opinie",
        "leave-review": "Zostaw Opinię",
        "all-reviews": "Wszystkie Opinie",
        "card-title-text": "Ile kosztuje rozwój strony internetowej!",
        "card-name1": "WIZYTÓWKA",
        "fromText": "Od",
        "currencyText": "USD",
        "fromText": "Od",
        "currencyText": "USD",

        "card-subtitle1": "Dla nowoczesnego biznesu tworzenie strony wizytówki jest wielką koniecznością",
        "card-name2": "LANDING PAGE",
        "card-subtitle2": "Dla tych, którzy dążą do osiągnięcia najlepszego wyniku.",
        "card-name3": "KORPORACYJNY",
        "card-subtitle3": "Najlepszy wybór do promowania swojej firmy w Internecie.",
        "btn-item1": "ZAMÓWIĆ",
        "fromText": "Od",
        "currencyText": "USD",
        "btn-item2": "ZAMÓWIĆ",
        "btn-item3": "ZAMÓWIĆ",
        "buttom-box-text": "Jeśli jesteś gotowy, aby zacząć, nie wahaj się! Zaufaj naszemu doświadczeniu i profesjonalizmowi w tworzeniu Twojej strony internetowej. Z nami Twój projekt zostanie zrealizowany szybko i skutecznie. Skontaktuj się z nami!",
        "buttom-box-text1": "Pracujemy na całym świecie",
        "text-modal": "Zostaw swoje dane kontaktowe, a my oddzwonimy",
        "label-name": "Imię",
        "label-phone": "Telefon",
        "label-email": "E-mail",
        "label-comment": "Komentarz",
        "checkbox-text": "Akceptuję warunki",
        "link-policy": "Polityka prywatności",
        "send-button": "Wyślij",
        "logo": "./svg/logo-pl.svg",
        "logo-modal": "./svg/logo-modal-pl.svg",
        "cook-trans": "Zgoda na pliki cookie",
        "cook-trans1": "Ta witryna korzysta z plików cookie, aby zapewnić lepsze i bardziej odpowiednie doświadczenie przeglądania witryny.",
        "cook-trans2": "więcej...",
        "cook-trans3": "Akceptuje",
        "cook-trans4": "Odrzucić",
        "services-title": "OFERUJEMY USŁUGI",
        "services-sub-title": "Dla małych i średnich firm",
        "services-description": "Dla udanego biznesu ważne jest posiadanie przedstawiciela w cyfrowym świecie. Strona internetowa to Twój przedstawiciel online, który zawsze jest w kontakcie z Twoimi klientami i dostarcza wszelkich niezbędnych informacji o Twoich usługach, produktach i firmie. Różne strony mają różne możliwości: im bardziej profesjonalna strona, tym większą wartość przynosi. Zamawiając u nas rozwój strony, otrzymasz nie tylko nowoczesny i unikalny projekt, ale także skuteczne narzędzie do przyciągania nowych klientów i rozwoju Twojego biznesu.",
        "anime-title": "Używamy",
        "services-main-title": "NASZE USŁUGI",
        "service-web-design-title": "Projektowanie stron internetowych",
        "service-web-design-description": "Nowoczesne projektowanie stron internetowych to połączenie estetyki i funkcjonalności, które pomaga tworzyć skuteczne i atrakcyjne strony internetowe. Nasze rozwiązania w zakresie projektowania stron internetowych sprawiają, że Twoja firma jest widoczna i atrakcyjna dla klientów, zapewniając najlepsze doświadczenia użytkownika.",
        "service-marketing-title": "Marketing",
        "service-marketing-description": "Skuteczny marketing to klucz do sukcesu Twojej firmy. Nasze strategie pomogą Ci przyciągnąć nowych klientów, zwiększyć rozpoznawalność marki i zwiększyć sprzedaż. Zaufaj nam w promowaniu swojego biznesu i zobacz realne rezultaty.",
        "service-graphics-title": "Grafika",
        "service-graphics-description": "Wysokiej jakości grafika to podstawa atrakcyjności wizualnej Twojej marki. Nasze kreatywne rozwiązania pomogą Ci wyróżnić się na tle konkurencji i skutecznie przekazać Twoje pomysły klientom. Zaufaj nam, aby stworzyć unikalne materiały wizualne dla Twojej firmy.",
        "service-data-analysis-title": "Analiza danych",
        "service-data-analysis-description": "Analiza danych to klucz do zrozumienia Twojego biznesu i podejmowania świadomych decyzji. Nasze usługi analizy danych pomogą Ci zidentyfikować ważne trendy, zoptymalizować procesy i poprawić efektywność. Zaufaj nam w analizie danych, a my przekształcimy je w cenne informacje dla Twojego sukcesu.",
        "service-app-development-title": "Tworzenie aplikacji",
        "service-app-development-description": "Twórz innowacyjne i przyjazne dla użytkownika aplikacje razem z nami. Nasz zespół deweloperów zapewnia wysoką jakość, funkcjonalność i bezpieczeństwo Twoich aplikacji mobilnych i internetowych. Zaufaj nam w realizacji swoich pomysłów, a my pomożemy Ci osiągnąć nowe wysokości w cyfrowym świecie.",
        "service-web-development-title": "Tworzenie stron internetowych",
        "service-web-development-description": "Profesjonalne tworzenie stron internetowych to droga do sukcesu w przestrzeni online. Tworzymy przyjazne dla użytkownika, szybkie i adaptacyjne strony internetowe, które przyciągają uwagę i zatrzymują odwiedzających. Zaufaj nam w tworzeniu Twojego zasobu internetowego, a stanie się on skutecznym narzędziem do rozwoju Twojej firmy.",
        "service-payment-systems-title": "Systemy płatności",
        "service-payment-systems-description": "Niezawodne systemy płatności to podstawa nowoczesnego biznesu. Oferujemy integrację bezpiecznych i wygodnych rozwiązań płatniczych, które zapewniają szybkie i niezawodne transakcje. Zaufaj nam w konfiguracji systemów płatności, a Twoi klienci docenią wygodę i bezpieczeństwo zakupów.",
        "service-network-title": "Sieć",
        "service-network-description": "Nowoczesna sieć to podstawa efektywnego i nieprzerwanego funkcjonowania Twojej firmy. Oferujemy profesjonalne ustawienia i wsparcie infrastruktury sieciowej, zapewniając wysoką prędkość, niezawodność i bezpieczeństwo. Zaufaj nam w kwestii Twojej sieci, a my gwarantujemy stabilne połączenie i optymalną pracę wszystkich systemów.",
        "contact-title": "Skontaktuj się z nami",
        "contact-description": "Skorzystaj z poniższego formularza, aby się z nami skontaktować. Wprowadź swoje imię, adres e-mail, telefon i wiadomość, a my wkrótce się z Tobą skontaktujemy.",
        "contact-label-name": "Imię",
        "contact-placeholder-name": "Imię",
        "contact-label-email": "Email",
        "contact-placeholder-email": "Email",
        "contact-label-tel": "Telefon",
        "contact-placeholder-tel": "+380",
        "contact-placeholder-comment": "Wiadomość",
        "contact-submit": "Wyślij",
        "contact-title": "Skontaktuj się z nami",
        "contact-description": "Skorzystaj z poniższego formularza, aby się z nami skontaktować. Wprowadź swoje imię, adres e-mail, telefon i wiadomość, a my wkrótce się z Tobą skontaktujemy.",
        "contact-placeholder-name": "Imię",
        "contact-placeholder-email": "Email",
        "contact-placeholder-tel": "+380",
        "contact-placeholder-comment": "Wiadomość",
        "contact-submit": "Wyślij",
        "prices-title": "Ile kosztuje stworzenie strony internetowej",
    "prices-subtitle": "Koszt tworzenia strony internetowej zależy od wielu czynników. Ceny podane w naszej tabeli nie są ostateczne i mogą się zmieniać w zależności od konkretnych wymagań i zadań, które nam postawisz.",
    "prices-main-factors": "Główne czynniki wpływające na koszt:",
    "prices-subtitle-factors": "Rodzaj strony: Wizytówka, strona korporacyjna, sklep internetowy, strona ekskluzywna – każdy rodzaj ma swoje cechy i wymagania dotyczące rozwoju. Funkcjonalność: Im więcej funkcji i możliwości powinna mieć Twoja strona, tym więcej czasu i zasobów potrzeba na jej stworzenie. Projekt: Unikalny i skomplikowany projekt wymaga więcej czasu na rozwój, co wpływa na ostateczny koszt. Integracje: Podłączanie dodatkowych usług i integracji z innymi systemami może również wpłynąć na cenę. Terminy: Jeśli potrzebujesz strony internetowej w najkrótszym czasie, może to wpływać na koszt.",
    "site-type-business-card": "Wizytówka",
    "site-type-corporate": "Strona korporacyjna",
    "site-type-online-store": "Sklep internetowy",
    "site-type-turnkey": "Strona pod klucz",
    "site-type-small-business": "Strona dla małych i średnich firm",
    "site-type-large-business": "Strona dla dużych firm",
    "term-from": "Od",
    "term-days": "dni",
    "price-from": "od",
    "currency-usd": "USD",
    "order-button": "Zamów",
    "price-table-desktop-header-type": "Rodzaj strony",
    "price-table-desktop-header-price": "Cena, USD",
    "price-table-desktop-header-order": "Zamów",
    "our-approach-title": "Nasze podejście:",
    "our-approach-subtitle": "Zawsze koncentrujemy się na potrzebach naszych klientów i jesteśmy gotowi zaoferować optymalne rozwiązania odpowiadające Twoim możliwościom budżetowym. Na przykład dla małych firm możemy zaoferować stronę szablonową, która będzie tańsza, ale jednocześnie funkcjonalna i atrakcyjna. Jeśli potrzebujesz ekskluzywnej strony z unikalnym projektem i rozszerzonymi możliwościami, koszt będzie wyższy.",
    "pricing-flexibility-title": "Elastyczność cenowa:",
    "pricing-flexibility-subtitle": "Zawsze jesteśmy otwarci na dyskusje i elastyczni w ustalaniu cen. Nasi specjaliści pomogą Ci wybrać najlepszą opcję, biorąc pod uwagę Twoje potrzeby i możliwości. Otrzymasz indywidualne podejście i profesjonalne wykonanie każdego projektu.",
    "reviews-hero-title": "Oto niektóre z naszych nagród i osiągnięć.",
        "facebook-title": "Facebook",
        "facebook-average-rating": "Średnia ocena na Facebooku",
        "facebook-rating": "4.8",
        "google-title": "Google",
        "google-average-rating": "Średnia ocena w Google",
        "google-rating": "4.6",
        "reviewsTitle": "Opinie naszych klientów",
        "reviewName1": "Aleksander",
        "reviewText1": "Zespół profesjonalistów szybko i sprawnie stworzył naszą stronę korporacyjną. Bardzo zadowolony ze współpracy!",
        "reviewName2": "Anna",
        "reviewText2": "Świetne wsparcie naszej strony. Wszystkie problemy są rozwiązywane szybko i profesjonalnie. Polecam!",
        "reviewName3": "Marek",
        "reviewText3": "Zespół ekspertów szybko stworzył naszą firmową stronę internetową. Jestem bardzo zadowolony ze współpracy!",
        "reviewName4": "Ewa",
        "reviewText4": "Doskonała obsługa i wsparcie naszego sklepu internetowego. Bardzo wdzięczni za pracę!",
        "reviewName5": "Igor",
        "reviewText5": "Rozwój naszej strony przebiegł bez zarzutu. Zespół jest zawsze w kontakcie i gotowy do pomocy w każdej chwili.",
        "reviewName6": "Magda",
        "reviewText6": "Świetna obsługa i wsparcie naszej strony internetowej. Bardzo dziękujemy za pracę!",
        "reviewName7": "Olena",
        "reviewText7": "Rozwój strony internetowej został wykonany bardzo szybko i profesjonalnie. Zespół uwzględnił wszystkie nasze życzenia. Polecamy!",
        "reviewName8": "Krzysztof",
        "reviewText8": "Zamówienie strony internetowej przeszło gładko. Firma dostarczyła wszystko na czas i zgodnie z wymaganiami. Polecam!",
        "leaveGoogleReview": "Zostaw opinię w",
        "googleText": "Google",
        "leaveFacebookReview": "Zostaw opinię w",
        "facebookText": "Facebook",
        "contactAdvice": "Jeśli masz pytania lub chcesz otrzymać konsultację, skontaktuj się z nami, a my z przyjemnością pomożemy Ci opracować stronę internetową, która najlepiej odpowiada Twoim potrzebom i budżetowi.",



    },
    "uk": {
        "title": "Ua",
        "services": "Послуги",
        "prices": "Ціни",
        "reviews": "Відгуки",
        "contact": "Контакт",
        "promotions": "Акції",
        "logo": "./svg/logo-modal.svg",
        "heroSubtitle1": "Створення дизайну, розробка сайту під ключ з просуванням його в Google до топових позицій",
        "heroSubtitle2": "Звертаючись до нашої веб-студії ви отримаєте максимальний результат за доступною ціною для вашого бізнесу.",
        "orderButton": "Замовити сайт",
        "clientsCount": "200+",
        "satisfiedClients": "Задоволених клієнтів",
        "company-title-tran": "Для чого потрібен",
        "company-title-tran1": "Сайт",
        "company-title-tran2": "В першу чергу",
        "company-title-tran3": "це сучасний бізнес!",
        "company-text": "Середньостатистичний користувач проводить 6 годин на день в інтернеті (джерело GlobalWebIndex). Малі, середні та великі організації за допомогою створення сайту займають нішу в інтернет-середовищі, щоб:",
        "company-list-item1": "Розповісти клієнтам та партнерам про себе.",
        "company-list-item2": "Залучати покупця та продавати.",
        "company-list-item3": "Отримувати прибуток від продажу.",
        "company-list-item4": "Заощадити час обробки замовлень, використовуючи докладні форми.",
        "company-list-item5": "Отримати миттєвий доступ до закордонних клієнтів.",
        "company-list-item6": "Використання сайту як платформи для демонстрації унікальності вашого бренду.",
        "partners-txt": "Спрощуємо процеси для",
        "partners-title-txt": "Розробки Вашого Сайту",
        "partners-description": "Наші веб-сайти відображають індивідуальність кожного клієнта, його характеристики, уподобання та загальну концепцію бізнесу. Ми піклуємося про те, щоб ваш сайт став продовженням вашої компанії у цифровому просторі.",
        "partners-hero-list1": "Нам довіряють лідери.",
        "partners-hero-list2": "Довіра, підтверджена досвідом.",
        "partners-hero-list3": "Постійна підтримка для наших клієнтів.",
        "partners-title": "Бренди, які нам довіряють",
        "partners-sub-title": "довіряють",
        "construction-title": "Етапи розробки",
        "construction-subtitle": "Якісне виконання кожного з перерахованих етапів – це гарантія успіху всього Вашого проекту",
        "step1-title": "Замовлення",
        "step1-text": "Залишіть заявку і наш менеджер зв'яжеться з Вами протягом 24h.",
        "step2-title": "Виявлення потреби",
        "step2-text": "Обговоримо всі деталі проекту, та складемо технічне завдання.",
        "step3-title": "Структура сайту",
        "step3-text": "Розробимо структуру сайту, його логіку та прототип кожної сторінки.",
        "step4-title": "Web-дизайн",
        "step4-text": "Створимо унікальний дизайн за найновішими технологіями.",
        "step5-title": "Адаптивна верстка",
        "step5-text": "Зробимо адаптивну та кросбраузерну верстку.",
        "step6-title": "Інтеграція з CMS",
        "step6-text": "Підключимо готову верстку до CMS для подальшого керування сайтом.",
        "step7-title": "Аналіз конкурентів",
        "step7-text": "Проводимо ретельний аналіз галузі та конкуренції для Вашого сайту.",
        "step8-title": "Тестування",
        "step8-text": "Протестуємо сайт на «баги» та перенесемо його на ваш сервер.",
        "revie-translate": "Відгуки наших клієнтів.",
        "revie-translate1": "Переглянути Відгуки.",
        "review-title": "Відгуки наших клієнтів",
        "review-link": "Переглянути Відгуки",
        "leave-review": "Залишити відгук",
        "all-reviews": "Усі відгуки",
        "card-title-text": "Скільки коштує розробка сайту !",
        "card-name1": "САЙТ ВІЗИТКА",
        "card-subtitle1": "Для сучасного бізнесу великою необхідністю є розробка сайту-візитки",
        "card-name2": "LANDING PAGE",
        "card-subtitle2": "Для тих, хто прагне отримувати найкращий результат.",
        "card-name3": "КОРПОРАТИВНИЙ",
        "card-subtitle3": "Найкращий вибір для просування своєї справи в інтернеті.",
        "btn-item1": "ЗАМОВИТИ",
        "btn-item2": "ЗАМОВИТИ",
        "fromText": "Від",
        "fromText": "Від",
        "fromText": "Від",
        "currencyText": "USA",
        "currencyText": "USA",
        "currencyText": "USD",
        "btn-item3": "ЗАМОВИТИ",
        "buttom-box-text": "Якщо ви готові розпочати, не зволікайте! Довіртеся нашому досвіду та професіоналізму у розробці вашого сайту. З нами ваш проєкт буде реалізовано швидко та ефективно. Зв'яжіться з нами!",
        "buttom-box-text1": "Працюємо по всьому світу",
        "text-modal": "Залиште свої контакти і ми вам передзвонимо",
        "label-name": "Ім'я",
        "label-phone": "Телефон",
        "label-email": "E-mail",
        "label-comment": "Коментар",
        "checkbox-text": "Я приймаю умови",
        "link-policy": "Політика конфіденційності",
        "send-button": "Відправити",
        "logo": "./svg/logo-modal.svg",
        "logo-modal": "./svg/logo-modal.svg",
        "cook-trans": "Згода на файли cookie",
        "cook-trans1": "Цей вебсайт використовує файли cookie, щоб допомогти вам мати кращий і більш релевантний досвід перегляду на вебсайті.",
        "cook-trans2": "Дізнатися більше...",
        "cook-trans3": "Прийняти",
        "cook-trans4": "Відхилити",
        "services-title": "ПРОПОНУЄМО ПОСЛУГИ",
        "services-sub-title": "Для малого та середнього бізнесу",
        "services-description": "Для успішного бізнесу важливо мати представника у цифровому світі. Вебсайт – це ваш онлайн представник, який завжди на зв'язку з вашими клієнтами та надає всю необхідну інформацію про ваші послуги, продукти та компанію. Різні сайти мають різні можливості: чим більш професійний сайт, тим більшу цінність він приносить. Замовивши у нас розробку сайту, ви отримаєте не лише сучасний та унікальний дизайн, але й ефективний інструмент для залучення нових клієнтів та розвитку вашого бізнесу.",
        "anime-title": "З ЧИМ МИ ПРАЦЮЄМО",
        "services-main-title": "НАШІ ПОСЛУГИ",
        "service-web-design-title": "Веб дизайн",
        "service-web-design-description": "Сучасний веб дизайн – це поєднання естетики та функціональності, яке допомагає створювати ефективні та привабливі веб-сайти. Наші рішення з веб дизайну роблять ваш бізнес видимим і привабливим для клієнтів, забезпечуючи найкращий користувацький досвід.",
        "service-marketing-title": "Маркетинг",
        "service-marketing-description": "Ефективний маркетинг – це ключ до успіху вашого бізнесу. Наші стратегії допоможуть вам залучити нових клієнтів, підвищити впізнаваність бренду та збільшити продажі. Довірте нам просування вашого бізнесу і побачите реальні результати.",
        "service-graphics-title": "Графіка",
        "service-graphics-description": "Високоякісна графіка – це основа візуальної привабливості вашого бренду. Наші креативні рішення допоможуть вам виділитися серед конкурентів та ефективно донести ваші ідеї до клієнтів. Довірте нам створення унікальних візуальних матеріалів для вашого бізнесу.",
        "service-data-analysis-title": "Аналіз даних",
        "service-data-analysis-description": "Аналіз даних – це ключ до розуміння вашого бізнесу та прийняття обґрунтованих рішень. Наші послуги з аналізу даних допоможуть вам виявити важливі тенденції, оптимізувати процеси та підвищити ефективність роботи. Довірте нам аналіз даних, і ми перетворимо їх на цінну інформацію для вашого успіху.",
        "service-app-development-title": "Розробка додатків",
        "service-app-development-description": "Створюйте інноваційні та зручні додатки разом з нами. Наша команда розробників забезпечить високу якість, функціональність і безпеку ваших мобільних та веб-додатків. Довірте нам реалізацію ваших ідей, і ми допоможемо вам досягти нових висот у цифровому світі.",
        "service-web-development-title": "Сайти",
        "service-web-development-description": "Професійна розробка сайтів – це шлях до успіху в онлайн-просторі. Ми створюємо зручні, швидкі та адаптивні веб-сайти, які привертають увагу та утримують відвідувачів. Довірте нам створення вашого веб-ресурсу, і він стане ефективним інструментом для розвитку вашого бізнесу.",
        "service-payment-systems-title": "Платіжні системи",
        "service-payment-systems-description": "Надійні платіжні системи – це основа сучасного бізнесу. Ми пропонуємо інтеграцію безпечних та зручних платіжних рішень, що забезпечують швидкі та надійні транзакції. Довірте нам налаштування платіжних систем, і ваші клієнти оцінять зручність і безпеку покупок.",
        "service-network-title": "Мережа",
        "service-network-description": "Сучасна мережа – це основа ефективного та безперебійного функціонування вашого бізнесу. Ми пропонуємо професійне налаштування і підтримку мережевої інфраструктури, забезпечуючи високу швидкість, надійність та безпеку. Довірте нам вашу мережу, і ми гарантуємо стабільне з'єднання та оптимальну роботу всіх систем.",
        "contact-title": "Зв'яжіться з нами",
        "contact-description": "Будь ласка, скористайтеся формою нижче, щоб зв'язатися з нами. Введіть своє ім'я, адресу електронної пошти, телефону та повідомлення, і ми незабаром зв’яжемося з вами.",
        "contact-label-name": "Ім'я",
        "contact-placeholder-name": "Ім'я",
        "contact-label-email": "Email",
        "contact-placeholder-email": "Email",
        "contact-label-tel": "Телефон",
        "contact-placeholder-tel": "+380",
        "contact-placeholder-comment": "Повідомлення",
        "contact-submit": "Відправити",
        "contact-title": "Зв'яжіться з нами",
        "contact-description": "Будь ласка, скористайтеся формою нижче, щоб зв'язатися з нами. Введіть своє ім'я, адресу електронної пошти, телефону та повідомлення, і ми незабаром зв’яжемося з вами.",
        "contact-placeholder-name": "Ім'я",
        "contact-placeholder-email": "Email",
        "contact-placeholder-tel": "+380",
        "contact-placeholder-comment": "Повідомлення",
        "contact-submit": "Відправити",
        "prices-title": "Скільки коштує зробити сайт",
    "prices-subtitle": "Вартість розробки сайту залежить від багатьох факторів. Ціни, наведені в нашій таблиці, не є кінцевими і можуть змінюватися в залежності від конкретних вимог та завдань, які ви ставите перед нами.",
    "prices-main-factors": "Основні фактори, що впливають на вартість:",
    "prices-subtitle-factors": "Тип сайту: Візитка, корпоративний сайт, інтернет-магазин, ексклюзивний сайт – кожен тип має свої особливості та вимоги до розробки. Функціональність: Чим більше функцій та можливостей повинен мати ваш сайт, тим більше часу та ресурсів потрібно на його створення. Дизайн: Унікальний та складний дизайн потребує більше часу на розробку, що впливає на кінцеву вартість. Інтеграції: Підключення додаткових сервісів та інтеграцій з іншими системами також може вплинути на ціну. Терміни виконання: Якщо вам потрібен сайт у найкоротші терміни, це може відобразитися на вартості.",
    "site-type-business-card": "Сайт візитка",
    "site-type-corporate": "Корпоративний сайт",
    "site-type-online-store": "Інтернет магазин",
    "site-type-turnkey": "Сайт під ключ",
    "site-type-small-business": "Сайт для малого та середнього бізнесу",
    "site-type-large-business": "Сайт для великого бізнесу",
    "term-from": "Від",
    "term-days": "днів",
    "price-from": "від",
    "currency-usd": "USD",
    "order-button": "Замовити",
    "price-table-desktop-header-type": "Тип сайту",
    "price-table-desktop-header-price": "Ціна, USD",
    "price-table-desktop-header-order": "Замовлення",
    "our-approach-title": "Наш підхід:",
    "our-approach-subtitle": "Ми завжди орієнтуємося на потреби наших клієнтів і готові запропонувати оптимальні рішення, що відповідають вашим бюджетним можливостям. Наприклад, для невеликого бізнесу ми можемо запропонувати шаблонний сайт, який буде коштувати дешевше, але водночас залишиться функціональним та привабливим. Якщо ж вам потрібен ексклюзивний сайт з унікальним дизайном та розширеними можливостями, вартість буде вищою.",
    "pricing-flexibility-title": "Гнучкість у ціноутворенні:",
    "pricing-flexibility-subtitle": "Ми завжди готові до обговорення та гнучкі в ціноутворенні. Наші фахівці допоможуть визначити найкращий варіант, враховуючи ваші потреби та можливості. Ви отримаєте індивідуальний підхід та професійне виконання кожного проекту.",
    "reviews-hero-title": "Тут зібрані деякі наші нагороди та досягнення.",
        "facebook-title": "Facebook",
        "facebook-average-rating": "Середня оцінка на Facebook",
        "facebook-rating": "4.8",
        "google-title": "Google",
        "google-average-rating": "Середня оцінка в Google",
        "google-rating": "4.6",
        "reviewsTitle": "Думки наших клієнтів",
        "reviewName1": "Олександр",
        "reviewText1": "Команда професіоналів швидко та якісно створила наш корпоративний сайт. Дуже задоволений співпрацею!",
        "reviewName2": "Анна",
        "reviewText2": "Чудова підтримка нашого сайту. Всі питання вирішуються оперативно та професійно. Рекомендую!",
        "reviewName3": "Марек",
        "reviewText3": "Зespół ekspertów szybko stworzył naszą firmową stronę internetową. Jestem bardzo zadowolony ze współpracy!",
        "reviewName4": "Єва",
        "reviewText4": "Відмінне обслуговування та підтримка нашого інтернет-магазину. Дуже вдячні за роботу!",
        "reviewName5": "Ігор",
        "reviewText5": "Розробка нашого сайту пройшла бездоганно. Команда постійно на зв'язку та готова допомогти в будь-який момент.",
        "reviewName6": "Магда",
        "reviewText6": "Świetna obsługa i wsparcie naszej strony internetowej. Bardzo dziękujemy za pracę!",
        "reviewName7": "Олена",
        "reviewText7": "Розробка веб-сайту була виконана дуже швидко та професійно. Команда врахувала всі наші побажання. Рекомендуємо!",
        "reviewName8": "Кшиштоф",
        "reviewText8": "Zamówienie strony internetowej przeszło gładko. Firma dostarczyła wszystko na czas i zgodnie z wymaganiami. Polecam!",
        "leaveGoogleReview": "Залиште відгук у",
        "googleText": "Google",
        "leaveFacebookReview": "Залиште відгук у",
        "facebookText": "Facebook",
        "contactAdvice": "Якщо у вас є питання або ви хочете отримати консультацію, звертайтеся до нас, і ми з радістю допоможемо вам розробити сайт, який найкраще відповідає вашим потребам та бюджету.",
        


    }
};

// Функція для визначення мови системи користувача
function getUserLanguage() {
    return navigator.language || navigator.userLanguage;
}

// Функція для встановлення мови
function setLanguage(language) {
    const lang = translations[language] ? language : 'en'; // Використовуємо англійську за замовчуванням

    document.getElementById('titleHeader').innerText = translations[lang].title;
    document.getElementById('titleMobile').innerText = translations[lang].title;

    // Оновлюємо текстові елементи
    document.querySelectorAll('[data-translate-key]').forEach(element => {
        const key = element.getAttribute('data-translate-key');
        if (translations[lang][key]) {
            element.innerText = translations[lang][key];
        }
    });

    // Оновлюємо логотипи
    document.getElementById('logoHeader').src = translations[lang].logo;
    document.getElementById('logoMobile').src = translations[lang].logo;

    // Оновлюємо URL
    const currentUrl = new URL(window.location);
    currentUrl.searchParams.set('lang', lang);
    window.history.pushState({}, '', currentUrl);

    // Зберігаємо вибір мови у localStorage
    localStorage.setItem('selectedLanguage', lang);
}

// Визначаємо мову користувача та встановлюємо відповідну мову на сайті при завантаженні
function initializeLanguage() {
    const urlParams = new URLSearchParams(window.location.search);
    const langFromUrl = urlParams.get('lang');
    const savedLang = localStorage.getItem('selectedLanguage');

    if (langFromUrl && translations[langFromUrl]) {
        setLanguage(langFromUrl);
    } else if (savedLang && translations[savedLang]) {
        setLanguage(savedLang);
    } else {
        const userLanguage = getUserLanguage().substring(0, 2); // Отримуємо перші 2 символи мови
        setLanguage(userLanguage);
    }
}

// Додаємо обробники подій для кнопок зміни мови
document.querySelectorAll('#languageButtonHeader, #languageButtonMobile').forEach(button => {
    button.addEventListener('click', function() {
        const menuId = this.id === 'languageButtonHeader' ? 'languageMenuHeader' : 'languageMenuMobile';
        document.getElementById(menuId).classList.toggle('show');
    });
});

// Додаємо обробник подій для вибору мови
document.querySelectorAll('.language-menu a').forEach(function(element) {
    element.addEventListener('click', function(event) {
        event.preventDefault();
        const lang = this.getAttribute('data-lang');
        setLanguage(lang);
        document.getElementById('languageMenuHeader').classList.remove('show');
        document.getElementById('languageMenuMobile').classList.remove('show');
    });
});

// Закриваємо меню, якщо користувач клацає поза його межами
window.onclick = function(event) {
    if (!event.target.matches('#languageButtonHeader') && !event.target.matches('#languageButtonMobile') &&
        !event.target.matches('#languageButtonHeader img') && !event.target.matches('#languageButtonMobile img')) {
        const dropdowns = document.getElementsByClassName("language-menu");
        for (let i = 0; i < dropdowns.length; i++) {
            const openDropdown = dropdowns[i];
            if (openDropdown.classList.contains('show')) {
                openDropdown.classList.remove('show');
            }
        }
    }
}

// Ініціалізуємо мову при завантаженні сторінки
initializeLanguage();
